name: Cooker
main: io.github.psgs.cooker.Cooker
description: Cooks stuff.
version: 1.1

commands:
   cook:
      description: Cooker cooking command.
      usage: /<command>
      permission: cooker.cook

permissions:
   cooker.cook:
      description: Allows you to cook stuff.
      default: op
